### ISSUE TITLE
Change the source of daily pollen data

### ISSUE THREAD

**Issue by lassevalentini** [Tomorrows-pollen-today/yesterdays-pollen-today#3]
The DMI RSS feed does not contain any data when the pollen count is low. 
This is an issue, as the source we use for predictions has correct counts for the whole year.

The daily collection of pollen count should be changed to fetch data from astma-allergi.dk, since it has high fidelity data.

**Comment by goibon** [comment]
@lassevalentini What is the status on this now that DMI has shut down their feed?

**Comment by lassevalentini** [comment]
Thisted issue is fixed in [PR4 Expansion pack 1](https://github.com/Tomorrows-pollen-today/yesterdays-pollen-today/pull/4). Ill close the issue.
